service: catastro-municipal-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: java21
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 30
  
  # VARIABLE IAM ROLE - Modifica este valor con tu ARN de IAM Role
  # Formato: arn:aws:iam::{ACCOUNT_ID}:role/{ROLE_NAME}
  iam:
    role: arn:aws:iam::946503249480:role/LabRole
  
  environment:
    QUARKUS_PROFILE: prod
    JAVA_TOOL_OPTIONS: >-
      -XX:+TieredCompilation 
      -XX:TieredStopAtLevel=1
      -Djava.awt.headless=true
      -Dquarkus.http.io-threads=2
      -Dquarkus.vertx.worker-pool-size=4
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_NAME: ${env:DB_NAME, 'catastro_db'}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    AWS_XRAY_TRACING_NAME: catastro-api

  tracing:
    lambda: true
    apiGateway: true

  logs:
    restApi:
      level: INFO
      executionLogging: true
      fullExecutionData: true

  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET_ID_1}
      - ${env:SUBNET_ID_2}

package:
  artifact: target/function.zip
  individually: false

functions:
  # ==================== ESTIMACION CRUD ====================
  estimacionApi:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    snapStart: true
    events:
      - http:
          path: /api/estimaciones
          method: post
      - http:
          path: /api/estimaciones/{id}
          method: get
      - http:
          path: /api/estimaciones/{id}
          method: put
      - http:
          path: /api/estimaciones/{id}
          method: delete
      - http:
          path: /api/estimaciones/lote/{loteId}
          method: get

  # ==================== FICHA CATASTRAL CRUD ====================
  fichaCatastralApi:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    snapStart: true
    events:
      - http:
          path: /api/fichas
          method: post
      - http:
          path: /api/fichas/{id}
          method: get
      - http:
          path: /api/fichas/{id}
          method: put
      - http:
          path: /api/fichas/{id}
          method: delete
      - http:
          path: /api/fichas/lote/{codigoLote}
          method: get

resources:
  Resources:
    # RDS PostgreSQL Instance
    CatastroRDSInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: catastro-db-${self:provider.stage}
        DBInstanceClass: db.t4g.micro
        Engine: postgres
        EngineVersion: '16.1'
        MasterUsername: ${env:DB_USER}
        MasterUserPassword: ${env:DB_PASSWORD}
        AllocatedStorage: 20
        MaxAllocatedStorage: 100
        StorageType: gp3
        StorageEncrypted: true
        BackupRetentionPeriod: 7
        PreferredBackupWindow: 03:00-04:00
        PreferredMaintenanceWindow: sun:04:00-sun:05:00
        MultiAZ: false
        PubliclyAccessible: false
        VPCSecurityGroups:
          - ${env:SECURITY_GROUP_ID}
        DBSubnetGroupName: ${env:DB_SUBNET_GROUP}
        EnablePerformanceInsights: true
        PerformanceInsightsRetentionPeriod: 7

plugins:
  - serverless-plugin-snapstart
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
